services:
  - type: web
    name: cardealer-backend
    runtime: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://cardealer-backend.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /app/database/database.sqlite
      - key: FILESYSTEM_DISK
        value: public
      - key: FILAMENT_ADMIN_NAME
        value: Admin
      - key: FILAMENT_ADMIN_EMAIL
        value: admin@admin.com
      - key: FILAMENT_ADMIN_PASSWORD
        value: change-me
